CONFIG_ZMK_KEYBOARD_NAME="AroundForty-LB"
CONFIG_BT_DEVICE_NAME="AroundForty-LB" 
CONFIG_BT_DEVICE_NAME_MAX=16
# =========================
# Pointing
# =========================
CONFIG_ZMK_MOUSE=y
CONFIG_INPUT=y
# Smooth scrolling
# CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
# =========================
# SPI / Hardware
# =========================
# =========================
# PMW3610
# =========================
CONFIG_PMW3610=y
CONFIG_PMW3610_SMART_ALGORITHM=y
# =========================
# Bluetooth / Battery
# =========================
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_BT_BAS=y
# =========================
# RGB
# =========================
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
